### ISSUE TITLE
Создать макет в Figma

### ISSUE THREAD

**Issue by Hardtmuth** [Hardtmuth/hexly_group_project_front#1]
Создать макет главной страницы

**Comment by programmer-kazarin** [comment]
Может просто скриншота с ticktick достаточно?

**Comment by Hardtmuth** [comment]
![Image](https://github.com/Hardtmuth/hexly_group_project_front/assets/23229721/9451bc61-44f6-43bc-8d47-ad3574f5f0a5)

**Comment by Vyacheslavorlov777** [comment]
![Image](https://github.com/Hardtmuth/hexly_group_project_front/assets/147432533/dcb5947e-1d21-4c5b-8195-6699434a8440)
